<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INTELLIAGENT1" failures="0" tests="3" name="FrameWork.FrameWork.ExcelDrivenRunning" time="19.784" errors="0" timestamp="2024-09-11T01:11:27 IST" skipped="0">
  <testcase classname="FrameWork.FrameWork.ExcelDrivenRunning" name="StandAloneTest2" time="7.803"/>
  <testcase classname="FrameWork.FrameWork.ExcelDrivenRunning" name="OrderHistoryTest" time="4.716"/>
  <testcase classname="FrameWork.FrameWork.ExcelDrivenRunning" name="StandAloneTest2" time="7.265"/>
  <system-out>
    <![CDATA[ErrorMessage validated successfully]]>
  </system-out>
</testsuite> <!-- FrameWork.FrameWork.ExcelDrivenRunning -->
