<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INTELLIAGENT1" failures="0" tests="3" name="FrameWork.FrameWork.StandaloneTest2" time="21.864" errors="0" timestamp="2024-09-11T12:41:42 IST" skipped="0">
  <testcase classname="FrameWork.FrameWork.StandaloneTest2" name="OrderHistoryTest" time="5.132"/>
  <testcase classname="FrameWork.FrameWork.StandaloneTest2" name="StandAloneTest2" time="7.347"/>
  <testcase classname="FrameWork.FrameWork.StandaloneTest2" name="StandAloneTest2" time="9.385"/>
  <system-out>
    <![CDATA[ErrorMessage validated successfully]]>
  </system-out>
</testsuite> <!-- FrameWork.FrameWork.StandaloneTest2 -->
