<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INTELLIAGENT1" failures="0" tests="3" name="FrameWork.FrameWork.StandaloneTest2" time="33.456" errors="0" timestamp="2024-09-05T15:30:46 IST" skipped="0">
  <testcase classname="FrameWork.FrameWork.StandaloneTest2" name="StandAloneTest2" time="12.338"/>
  <testcase classname="FrameWork.FrameWork.StandaloneTest2" name="StandAloneTest2" time="12.269"/>
  <testcase classname="FrameWork.FrameWork.StandaloneTest2" name="OrderHistoryTest" time="8.849"/>
  <system-out>
    <![CDATA[ErrorMessage validated successfully]]>
  </system-out>
</testsuite> <!-- FrameWork.FrameWork.StandaloneTest2 -->
